Resources
| where type contains "searchservice" or type == "microsoft.documentdb/databaseaccounts" or type == "microsoft.cognitiveservices/accounts" and kind == "AIServices" or kind == "OpenAI"
| project name, type, kind, location, resourceGroup, subscriptionId, tags,
SKU = sku.name,
creationDate = properties.dateCreated,
provisioningState = properties.provisioningState,
Projects = properties.associatedProjects,
disableLocalAuth = properties.disableLocalAuth,
customerManagedKey = iff(isnull(properties.customerManagedKey), "Microsoft-managed", properties.customerManagedKey),
customerManagedStorage = properties.customerManagedStorage,
publicNetworkAccess = properties.publicNetworkAccess, 
defaultAction = properties.networkAcls.defaultAction, 
bypass = properties.networkAcls.bypass,
Identity = identity.type,
isMigrated = properties.isMigrated
